site_name: Awesome MI theory
site_description: Simple notes and articles on MI theory
site_author: Sadiekh Sabrina
site_url: https://sadsabrina.github.io/awesome-mi-theory/

nav:
  - Home: index.md
  - Articles:
      - Introduction to MI: articles/introduction-to-mi.md
      - Basic Definitions: articles/basic-definiions.md
      - Key MI hypotheses : articles/hypotheses.md
      - Transformers : articles/transformers.md
      - CNN: articles/cnn.md

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight

extra_javascript:
  - js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
